// Enumeration of measurement types used in the flowsheet system
export enum MeasurementTypeEnum {
	// Vital Signs
	HEART_RATE = "HEART_RATE",
	RESPIRATORY_RATE = "RESPIRATORY_RATE",
	TEMPERATURE = "TEMPERATURE",
	SYSTOLIC_BP = "SYSTOLIC_BP",
	DIASTOLIC_BP = "DIASTOLIC_BP",
	OXYGEN_SATURATION = "OXYGEN_SATURATION",

	// Physical Assessment
	WEIGHT = "WEIGHT",
	BODY_CONDITION_SCORE = "BODY_CONDITION_SCORE",
	MUCOUS_MEMBRANE_COLOR = "MUCOUS_MEMBRANE_COLOR",
	CAPILLARY_REFILL_TIME = "CAPILLARY_REFILL_TIME",

	// Neurological Assessment
	GLASGOW_COMA_SCALE = "GLASGOW_COMA_SCALE",
	PUPIL_SIZE_LEFT = "PUPIL_SIZE_LEFT",
	PUPIL_SIZE_RIGHT = "PUPIL_SIZE_RIGHT",
	PAIN_SCORE = "PAIN_SCORE",

	// Laboratory Values
	GLUCOSE = "GLUCOSE",
	LACTATE = "LACTATE",
	PCV_HEMATOCRIT = "PCV_HEMATOCRIT",
	TOTAL_PROTEIN = "TOTAL_PROTEIN",

	// Fluid Management
	FLUID_INTAKE = "FLUID_INTAKE",
	URINE_OUTPUT = "URINE_OUTPUT",
}
